name: SSCA Plugin Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-ssca-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run SSCA Plugin Action
        uses: ./ # Uses the action in the root directory of the repository
        with:
          HARNESS_ACCOUNT_URL: 'https://qa.harness.io/gateway'
          HARNESS_ACCOUNT_ID: 'account123'
          HARNESS_ORG_ID: 'orgId'
          HARNESS_PROJECT_ID: 'project23'
          TOOL: 'Syft'
          FORMAT: 'spdx-json'
          TARGET: 'reetika1999/ssca-manager:latest'
